App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),

    url(r'^news/', views.news, name='news'),

    url(r'^jokes/', views.jokes, name='jokes'),

    url(r'^home/', views.home, name='home'),

    url(r'^getphone/', views.get_phone, name='get_phone'),

    url(r'^getticket/', views.get_ticket, name='get_ticket'),

    url(r'^search/', views.search, name='search'),

    url(r'^calc/', views.calc, name='calc'),

    url(r'^login/', views.login, name='login'),

    url(r'^addstudents/', views.add_students, name='add_students'),

    url(r'^getstudents/', views.get_students, name='get_students'),

    url(r'^getstudentswithpage/', views.get_students_with_page, name='get_students_with_page'),

    url(r'^getcode/', views.get_code, name='get_code'),
]

DjangoCache/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='app')),
]

App/models.py
from django.db import models


class Student(models.Model):
    s_name = models.CharField(max_length=16)
    s_age = models.IntegerField(default=15)

App/views.py
import random
from io import BytesIO
from time import sleep

# from django.core.cache import cache
from PIL import Image, ImageFont
from PIL.ImageDraw import Draw, ImageDraw
from django.core.cache import caches
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt

from App.models import Student
from App.utils import generate_code, get_color
from DjangoCache import settings


def index(request):
    return HttpResponse("Index")


# @cache_page(30)
def news(request):

    cache = caches['redis_backend']

    result = cache.get("news")

    if result:
        return HttpResponse(result)

    news_list = []

    for i in range(10):
        news_list.append("最近贸易战又开始了%d" % i)

    sleep(5)

    data = {
        'news_list': news_list
    }

    response = render(request, 'news.html', context=data)

    cache.set("news", response.content, timeout=60)

    return response


@cache_page(60, cache='redis_backend')
def jokes(request):

    sleep(5)

    return HttpResponse('JokeList')


def home(request):
    return HttpResponse("Home")


def get_phone(request):

    if random.randrange(100) > 95:
        return HttpResponse("恭喜你抢到了小米8")

    return HttpResponse("正在排队")


def get_ticket(request):

    return HttpResponse("还剩余99张满100-99")


def search(request):
    return HttpResponse("这是你搜索到的种子资源")


def calc(request):

    a = 250

    b = 250

    result = (a + b)/0

    return HttpResponse(result)


@csrf_exempt
def login(request):
    if request.method == "GET":
        return render(request, 'login.html')
    elif request.method == "POST":
        receive_code = request.POST.get("verify_code")
        store_code = request.session.get("verify_code")

        if receive_code.lower() != store_code.lower():
            return redirect(reverse('app:login'))
        return HttpResponse("登录成功")


def add_students(request):

    for i in range(100):

        student = Student()
        student.s_name = "小明%d" % i
        student.s_age = i

        student.save()

    return HttpResponse("学生创建成功")


def get_students(request):

    page = int(request.GET.get("page", 1))

    per_page = int(request.GET.get("per_page", 10))

    students = Student.objects.all()[per_page*(page-1): page * per_page]

    data = {
        "students": students
    }

    return render(request, 'students.html', context=data)


def get_students_with_page(request):

    page = int(request.GET.get("page", 1))

    per_page = int(request.GET.get("per_page", 10))

    students = Student.objects.all()

    paginator = Paginator(students, per_page)

    page_object = paginator.page(page)

    data = {
        "page_object": page_object,
        'page_range': paginator.page_range
    }

    return render(request, 'students_with_page.html', context=data)


def get_code(request):

    # 初始化画布，初始化画笔

    mode = "RGB"

    size = (200, 100)

    red = get_color()

    green = get_color()

    blue = get_color()

    color_bg = (red, green, blue)

    image = Image.new(mode=mode, size=size, color=color_bg)

    imagedraw = ImageDraw(image, mode=mode)

    imagefont = ImageFont.truetype(settings.FONT_PATH, 100)

    verify_code = generate_code()

    request.session['verify_code'] = verify_code

    for i in range(4):
        fill = (get_color(), get_color(), get_color())
        imagedraw.text(xy=(50*i, 0), text=verify_code[i], font=imagefont, fill=fill)

    for i in range(10000):
        fill = (get_color(), get_color(), get_color())
        xy = (random.randrange(201), random.randrange(100))
        imagedraw.point(xy=xy, fill=fill)

    fp = BytesIO()

    image.save(fp, "png")

    return HttpResponse(fp.getvalue(), content_type="image/png")

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/1.11.1/jquery.js"></script>

    <script type="text/javascript" src="{% static 'js/login.js' %}"></script>

</head>
<body>

<form action="{% url 'app:login' %}" method="post">

    <span>用户名:</span> <input type="text" name="username" placeholder="精神精神">

    <br>
    <span>验证码:</span><input type="text" name="verify_code" placeholder="请输入下图中的验证码">
    <br>
    <img src="{% url 'app:get_code' %}">
{#    <img src="#">#}

    <br>

    <button>精神一下</button>

</form>

</body>
</html>

templates/news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News</title>
</head>
<body>

<ul>
    {% for news in news_list %}
        <li>{{ news }}</li>
    {% endfor %}
        <li><a href="{% url 'app:calc' %}">中国已经不谈了，就是干</a></li>
</ul>

</body>
</html>

templates/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Students</title>
</head>
<body>
    <ul>
        {% for student in students %}
            <li>{{ student.s_name }}</li>
        {% endfor %}

    </ul>
</body>
</html>

templates/students_with_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StudentsWithPage</title>

    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">

    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/1.11.1/jquery.js"></script>

    <script type="text/javascript" src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.js"></script>

</head>
<body>

<ul>
    {% for student in page_object.object_list %}
        <li>{{ student.s_name }}</li>
    {% endfor %}

</ul>


<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_object.has_previous %}
            <li>
                <a href="{% url 'app:get_students_with_page' %}?page={{ page_object.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="disabled">
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

        {% endif %}

        {% for page_index in page_range %}
            {% ifequal page_index page_object.number %}
                <li class="active"><a href="{% url 'app:get_students_with_page' %}?page={{ page_index }}">{{ page_index }}</a></li>
            {% else %}
                <li><a href="{% url 'app:get_students_with_page' %}?page={{ page_index }}">{{ page_index }}</a></li>
            {% endifequal %}

        {% endfor %}

        {% if page_object.has_next %}
            <li>
                <a href="{% url 'app:get_students_with_page' %}?page={{ page_object.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="disabled">
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}

    </ul>
</nav>

</body>
</html>